name: "$(SourceBranchName)+$(BuildID)"

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ['*']

jobs:
  - job: build
    displayName: Build & Test
    timeoutInMinutes: 10
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      API_TEST_ENV_FILE_PATH: "tests/e2e/environments/local.postman_environment.json"
      PIP_CACHE_DIR: ".poetry"
    steps:
      - checkout: self

      - bash: echo "##vso[task.setvariable variable=BRANCH_NAME]`echo $(System.PullRequest.SourceBranch) | sed -r 's/[/|\\@":<>?*]+/-/g'`"
        displayName: Set and replace invalid characters in branch name

      - bash: 'echo "##vso[build.updatebuildnumber]$(BRANCH_NAME)+$(Build.BuildID)"'
        condition: eq(variables['Build.SourceBranchName'], 'merge')
        displayName: Update build ID if this is a pull request

      - task: UsePythonVersion@0
        displayName: "Use Python 3.8"
        inputs:
          versionSpec: "3.8"

      - bash: "sudo apt update && sudo apt-get install --yes default-jre default-jdk"
        displayName: Install apt dependencies

      - bash: "wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -"
        displayName: Add apt-key

      - bash: "curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -"
        displayName: Setup node

      - bash: sudo apt-get install -y nodejs
        displayName: Install node

      - bash: "python -m pip install --upgrade pip setuptools wheel && pip install poetry"
        displayName: Install python dependencies

      - task: Cache@2
        displayName: "Cache Python Dependencies"
        inputs:
          key: '"$(Agent.OS)" | "python" | poetry.lock'
          path: ".poetry"
          restoreKeys: |
            "$(Agent.OS)" | "python" | poetry.lock
            "$(Agent.OS)" | "python"

      - task: Cache@2
        displayName: "Cache Package NPM Dependencies"
        inputs:
          key: '"$(Agent.OS)" | "node" | package-lock.json'
          path: "node_modules"
          restoreKeys: |
            "$(Agent.OS)" | "node" | package-lock.json
            "$(Agent.OS)" | "node"

      - bash: "make install"
        displayName: Install repo

      - bash: "make check-licenses"
        displayName: Check licenses

      - bash: "make lint"
        displayName: Lint

      - bash: "make publish"
        displayName: Compile Spec

      - bash: "make release"
        displayName: Build Release Package

      - publish: dist/
        artifact: identity-service-$(Build.BuildNumber)
