name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Identity-Service-Build"
    trigger:
      branches:
        exclude:
          - master
          - refs/heads/master
          - refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    ping: false
    jinja_templates:
      IDENTITY_TARGET_SERVER: identity-server
      VARIABLES_KVM: identity-service-variables
      ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
    apigee_deployments:
      - environment: internal-dev
        tests:
          functional_test:
            steps:
              - template: templates/run-integration-tests.yml
                parameters:
                  service_name: ${{ variables.service_name }}
            test_app_attributes:
              asid: 12345
            test_app_callback_url: "test"
          non_functional_test:
            steps:
              - bash: echo 'this is a test'
