name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Identity-Service-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    ping: false
    jinja_templates:
      IDENTITY_TARGET_SERVER: identity-server
      VARIABLES_KVM: identity-service-variables
      ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
      NUM_RANDOM_LONG_INTS_FOR_STATE: 4
    config_ids:
      - /ptl/azure-devops/env-internal-dev/test-app/internal-testing-internal-dev/CLIENT_ID
      - /ptl/azure-devops/env-internal-dev/test-app/internal-testing-internal-dev/CLIENT_SECRET
      - /ptl/azure-devops/env-internal-dev/test-app/internal-testing-internal-dev/VALID_UNAPPROVED_CLIENT_ID
      - /ptl/azure-devops/env-internal-dev/test-app/internal-testing-internal-dev/VALID_UNAPPROVED_CLIENT_SECRET
      - /ptl/app-credentials/internal-dev/INTERNAL_TESTING_WITH_VALID_ASID_SECRET
      - /ptl/app-credentials/internal-dev/INTERNAL_TESTING_WITH_VALID_ASID_KEY
    secret_ids:
      - ptl/app-credentials/internal-dev/INTERNAL_TESTING_WITHOUT_ASID_KEY
      - ptl/app-credentials/internal-dev/INTERNAL_TESTING_WITHOUT_ASID_SECRET
      - ptl/app-credentials/internal-dev/INTERNAL_TESTING_WITH_ASID_KEY
      - ptl/app-credentials/internal-dev/INTERNAL_TESTING_WITH_ASID_SECRET
    apigee_deployments:
      - environment: internal-dev
        post_deploy:
          - template: ./templates/run-integration-tests.yml
            parameters:
              service_name: ${{ variables.service_name }}
      - environment: internal-dev-sandbox
      - environment: internal-qa
        depends_on: 
          - internal_dev
      - environment: internal-qa-sandbox
        depends_on: 
          - internal_dev
      - environment: ref
      - environment: dev
      - environment: int
      - environment: int
        stage_name: int_no_smartcard
        fully_qualified_service_name: identity-service-int-no-smartcard
        service_base_path: oauth2-no-smartcard
        jinja_templates:
          IDENTITY_TARGET_SERVER: identity-server-no-smartcard
          VARIABLES_KVM: identity-service-variables-no-smartcard
          ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted-no-smartcard
          NUM_RANDOM_LONG_INTS_FOR_STATE: 4
      - environment: prod
