name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Identity-Service-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    enable_monitoring: true
    enable_status_monitoring: true
    jinja_templates:
      IDENTITY_PROVIDER_CIS2: cis2
      IDENTITY_PROVIDER_NHS_LOGIN: nhs-login
      VARIABLES_KVM: identity_service_config
      ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
      NUM_RANDOM_LONG_INTS_FOR_STATE: 4
      RATELIMITING: ${{ variables.ratelimiting }}
    apigee_deployments:
      - environment: internal-dev
        post_deploy:
          - template: ./templates/run-integration-tests.yml
      - environment: internal-dev-sandbox
      - environment: internal-qa
        depends_on:
          - internal_dev
      - environment: internal-dev
        service_name: ${{ variables.service_name }}-mock
        short_service_name: ${{ variables.short_service_name }}-mock
        stage_name: internal_dev_mock
        service_base_path: ${{ variables.service_base_path }}-mock
        jinja_templates:
          IDENTITY_PROVIDER_CIS2: cis2-keycloak
          IDENTITY_PROVIDER_NHS_LOGIN: nhs-login
          VARIABLES_KVM: identity_service_config_keycloak
          ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
          NUM_RANDOM_LONG_INTS_FOR_STATE: 4
          RATELIMITING: ${{ variables.ratelimiting }}
      - environment: internal-qa
        depends_on:
          - internal_dev
        stage_name: internal_qa_smartcard
        fully_qualified_service_name: identity-service-internal-qa-int
        service_base_path: ${{ variables.service_base_path }}-int
        jinja_templates:
          IDENTITY_PROVIDER_CIS2: cis2-int
          IDENTITY_PROVIDER_NHS_LOGIN: nhs-login-int
          VARIABLES_KVM: identity_service_config_int
          ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
          NUM_RANDOM_LONG_INTS_FOR_STATE: 4
          RATELIMITING: ${{ variables.ratelimiting }}
      - environment: internal-qa
        service_name: ${{ variables.service_name }}-mock
        short_service_name: ${{ variables.short_service_name }}-mock
        stage_name: internal_qa_mock
        service_base_path: ${{ variables.service_base_path }}-mock
        jinja_templates:
          IDENTITY_PROVIDER_CIS2: cis2-keycloak
          IDENTITY_PROVIDER_NHS_LOGIN: nhs-login
          VARIABLES_KVM: identity_service_config_keycloak
          ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
          ENCRYPTED_VARIABLES_KVM_KEY_CLIENT_SECRET: keycloak_client_secret
          NUM_RANDOM_LONG_INTS_FOR_STATE: 4
          RATELIMITING: ${{ variables.ratelimiting }}
      - environment: internal-qa-sandbox
        depends_on:
          - internal_dev
      - environment: ref
      - environment: ref
        service_name: ${{ variables.service_name }}-mock
        short_service_name: ${{ variables.short_service_name }}-mock
        stage_name: ref_mock
        service_base_path: ${{ variables.service_base_path }}-mock
        jinja_templates:
          IDENTITY_PROVIDER_CIS2: cis2-keycloak
          IDENTITY_PROVIDER_NHS_LOGIN: nhs-login
          VARIABLES_KVM: identity_service_config_keycloak
          ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
          ENCRYPTED_VARIABLES_KVM_KEY_CLIENT_SECRET: keycloak_client_secret
          NUM_RANDOM_LONG_INTS_FOR_STATE: 4
          RATELIMITING: ${{ variables.ratelimiting }}
      - environment: dev
      - environment: sandbox # required for hello-world https://portal.developer.nhs.uk/docs/hello-world-sandbox/1/routes/hello/application/get
      - environment: int
      - environment: int
        service_name: ${{ variables.service_name }}-mock
        short_service_name: ${{ variables.short_service_name }}-mock
        stage_name: int_mock
        service_base_path: ${{ variables.service_base_path }}-mock
        jinja_templates:
          IDENTITY_PROVIDER_CIS2: cis2-keycloak
          IDENTITY_PROVIDER_NHS_LOGIN: nhs-login
          VARIABLES_KVM: identity_service_config_keycloak
          ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
          ENCRYPTED_VARIABLES_KVM_KEY_CLIENT_SECRET: keycloak_client_secret
          NUM_RANDOM_LONG_INTS_FOR_STATE: 4
          RATELIMITING: ${{ variables.ratelimiting }}
      - environment: int
        stage_name: int_no_smartcard
        fully_qualified_service_name: identity-service-int-no-smartcard
        service_base_path: oauth2-no-smartcard
        jinja_templates:
          IDENTITY_PROVIDER_CIS2: cis2-no-smartcard
          IDENTITY_PROVIDER_NHS_LOGIN: identity-server-no-smartcard
          VARIABLES_KVM: identity_service_config_no_smartcard
          ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted-no-smartcard
          NUM_RANDOM_LONG_INTS_FOR_STATE: 4
          RATELIMITING: ${{ variables.ratelimiting }}
      - environment: prod
