name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/APM-1163-deploy-dev-app
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Identity-Service-Build"
    trigger:
      branches:
        exclude:
          - master
          - refs/heads/master
          - refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    ping: false
    jinja_templates:
      IDENTITY_TARGET_SERVER: identity-server
      VARIABLES_KVM: identity-service-variables
      ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
    config_ids:
      - /ptl/azure-devops/env-internal-dev/test-app/internal-testing-internal-dev/CLIENT_ID
      - /ptl/azure-devops/env-internal-dev/test-app/internal-testing-internal-dev/CLIENT_SECRET
    post_deploy:
      - template: templates/run-integration-tests.yml
        parameters:
          service_name: ${{ variables.service_name }}
