name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Identity-Service-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    enable_monitoring: true
    enable_status_monitoring: true
    jinja_templates:
      IDENTITY_PROVIDER_CIS2: cis2-keycloak
      IDENTITY_PROVIDER_NHS_LOGIN: nhs-login-keycloak
      VARIABLES_KVM: identity_service_config_keycloak
      ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
      ENCRYPTED_VARIABLES_KVM_KEY_CLIENT_SECRET: keycloak_client_secret
      NUM_RANDOM_LONG_INTS_FOR_STATE: 4
      RATELIMITING: ${{ variables.ratelimiting }}
    apigee_deployments:
      # INTERNAL-DEV
      - environment: internal-dev
        service_name: ${{ variables.service_name }}-mock
        short_service_name: ${{ variables.short_service_name }}-mock
        stage_name: internal_dev_mock
        service_base_path: ${{ variables.service_base_path }}-mock
        post_deploy:
          - template: ./templates/run-integration-tests.yml
      - environment: internal-dev
        service_name: ${{ variables.service_name }}
        short_service_name: ${{ variables.short_service_name }}
        stage_name: internal_dev
        service_base_path: ${{ variables.service_base_path }}
        jinja_templates:
          IDENTITY_PROVIDER_CIS2: cis2-keycloak
          IDENTITY_PROVIDER_NHS_LOGIN: nhs-login-keycloak
          VARIABLES_KVM: identity_service_config
          ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
          NUM_RANDOM_LONG_INTS_FOR_STATE: 4
          RATELIMITING: ${{ variables.ratelimiting }}

      # INTERNAL-DEV-SANDBOX
      - environment: internal-dev-sandbox
        service_name: ${{ variables.service_name }}-mock
        short_service_name: ${{ variables.short_service_name }}-mock
        stage_name: internal_dev_sandbox_mock
        service_base_path: ${{ variables.service_base_path }}-mock
      - environment: internal-dev-sandbox
        service_name: ${{ variables.service_name }}
        short_service_name: ${{ variables.short_service_name }}
        stage_name: internal_dev_sandbox
        service_base_path: ${{ variables.service_base_path }}
        jinja_templates:
          IDENTITY_PROVIDER_CIS2: cis2-keycloak
          IDENTITY_PROVIDER_NHS_LOGIN: nhs-login-keycloak
          VARIABLES_KVM: identity_service_config
          ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
          NUM_RANDOM_LONG_INTS_FOR_STATE: 4
          RATELIMITING: ${{ variables.ratelimiting }}

      # INTERNAL_QA
      - environment: internal-qa
        service_name: ${{ variables.service_name }}-mock
        short_service_name: ${{ variables.short_service_name }}-mock
        stage_name: internal_qa_mock
        service_base_path: ${{ variables.service_base_path }}-mock
      - environment: internal-qa
        service_name: ${{ variables.service_name }}
        short_service_name: ${{ variables.short_service_name }}
        stage_name: internal_qa
        service_base_path: ${{ variables.service_base_path }}
        jinja_templates:
          IDENTITY_PROVIDER_CIS2: cis2-keycloak
          IDENTITY_PROVIDER_NHS_LOGIN: nhs-login-keycloak
          VARIABLES_KVM: identity_service_config
          ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
          NUM_RANDOM_LONG_INTS_FOR_STATE: 4
          RATELIMITING: ${{ variables.ratelimiting }}
      - environment: internal-qa # int backend
        stage_name: internal_qa_smartcard
        fully_qualified_service_name: identity-service-internal-qa-int
        service_base_path: ${{ variables.service_base_path }}-int
        jinja_templates:
          IDENTITY_PROVIDER_CIS2: cis2-int
          IDENTITY_PROVIDER_NHS_LOGIN: nhs-login-int
          VARIABLES_KVM: identity_service_config_int
          ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
          NUM_RANDOM_LONG_INTS_FOR_STATE: 4
          RATELIMITING: ${{ variables.ratelimiting }}

      # INTERNAL_QA_SANDBOX
      - environment: internal-qa-sandbox
        service_name: ${{ variables.service_name }}-mock
        short_service_name: ${{ variables.short_service_name }}-mock
        stage_name: internal_qa_sandbox_mock
        service_base_path: ${{ variables.service_base_path }}-mock
      - environment: internal-qa-sandbox
        service_name: ${{ variables.service_name }}
        short_service_name: ${{ variables.short_service_name }}
        stage_name: internal_qa_sandbox
        service_base_path: ${{ variables.service_base_path }}
        jinja_templates:
          IDENTITY_PROVIDER_CIS2: cis2-keycloak
          IDENTITY_PROVIDER_NHS_LOGIN: nhs-login-keycloak
          VARIABLES_KVM: identity_service_config
          ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
          NUM_RANDOM_LONG_INTS_FOR_STATE: 4
          RATELIMITING: ${{ variables.ratelimiting }}

      # REF
      - environment: ref
        service_name: ${{ variables.service_name }}-mock
        short_service_name: ${{ variables.short_service_name }}-mock
        stage_name: ref_mock
        service_base_path: ${{ variables.service_base_path }}-mock
      - environment: ref
        service_name: ${{ variables.service_name }}
        short_service_name: ${{ variables.short_service_name }}
        stage_name: ref
        service_base_path: ${{ variables.service_base_path }}
        jinja_templates:
          IDENTITY_PROVIDER_CIS2: cis2-keycloak
          IDENTITY_PROVIDER_NHS_LOGIN: nhs-login-keycloak
          VARIABLES_KVM: identity_service_config
          ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
          NUM_RANDOM_LONG_INTS_FOR_STATE: 4
          RATELIMITING: ${{ variables.ratelimiting }}

      # DEV
      - environment: dev # real nhs-login, mock cis2
        jinja_templates:
          IDENTITY_PROVIDER_CIS2: cis2-keycloak
          IDENTITY_PROVIDER_NHS_LOGIN: nhs-login
          VARIABLES_KVM: identity_service_config
          ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
          NUM_RANDOM_LONG_INTS_FOR_STATE: 4
          RATELIMITING: ${{ variables.ratelimiting }}
      - environment: dev # both mocked
        service_name: ${{ variables.service_name }}-mock
        short_service_name: ${{ variables.short_service_name }}-mock
        stage_name: dev_mock
        service_base_path: ${{ variables.service_base_path }}-mock
      - environment: dev # dep
        service_name: ${{ variables.service_name }}-dep
        short_service_name: ${{ variables.short_service_name }}-dep
        stage_name: dep
        service_base_path: ${{ variables.service_base_path }}-dep
        jinja_templates:
          IDENTITY_PROVIDER_CIS2: cis2-dep
          IDENTITY_PROVIDER_NHS_LOGIN: nhs-login-keycloak
          VARIABLES_KVM: identity_service_config_dep
          ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
          ENCRYPTED_VARIABLES_KVM_KEY_CLIENT_SECRET: dep_client_secret
          NUM_RANDOM_LONG_INTS_FOR_STATE: 4
          RATELIMITING: ${{ variables.ratelimiting }}

      # SANDBOX
      - environment: sandbox
        service_name: ${{ variables.service_name }}-mock
        short_service_name: ${{ variables.short_service_name }}-mock
        stage_name: sandbox_mock
        service_base_path: ${{ variables.service_base_path }}-mock
      - environment: sandbox
        service_name: ${{ variables.service_name }}
        short_service_name: ${{ variables.short_service_name }}
        stage_name: sandbox
        service_base_path: ${{ variables.service_base_path }}
        jinja_templates:
          IDENTITY_PROVIDER_CIS2: cis2-keycloak
          IDENTITY_PROVIDER_NHS_LOGIN: nhs-login-keycloak
          VARIABLES_KVM: identity_service_config
          ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
          NUM_RANDOM_LONG_INTS_FOR_STATE: 4
          RATELIMITING: ${{ variables.ratelimiting }}

      # INT
      - environment: int
        jinja_templates:
          IDENTITY_PROVIDER_CIS2: cis2
          IDENTITY_PROVIDER_NHS_LOGIN: nhs-login
          VARIABLES_KVM: identity_service_config
          ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
          NUM_RANDOM_LONG_INTS_FOR_STATE: 4
          RATELIMITING: ${{ variables.ratelimiting }}
      - environment: int
        service_name: ${{ variables.service_name }}-mock
        short_service_name: ${{ variables.short_service_name }}-mock
        stage_name: int_mock
        service_base_path: ${{ variables.service_base_path }}-mock

      # PROD
      - environment: prod
        jinja_templates:
          IDENTITY_PROVIDER_CIS2: cis2
          IDENTITY_PROVIDER_NHS_LOGIN: nhs-login
          VARIABLES_KVM: identity_service_config
          ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
          NUM_RANDOM_LONG_INTS_FOR_STATE: 4
          RATELIMITING: ${{ variables.ratelimiting }}
