name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      endpoint: NHSDigital
  pipelines:
  - pipeline: Identity-Service-Build
    source: Identity-Service-Build
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    service_base_path: ${{ variables.service_base_path }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    apigee_deployments:
      - environment: internal-dev
      - environment: internal-qa
      - environment: internal-qa-sandbox
      - environment: ref
      - environment: dev
      - environment: int
      - environment: int
        fully_qualified_service_name: pipeline-service-int-no-smartcard
        service_base_path: dummy-no-smartcard
        stage_name: int_no_smartcard
      - environment: prod
    pre_template:
      - template: "templates/identity-service-templating.yml"
        parameters:
          service_name: ${{ variables.service_name }}
          variables_kvm: "identity-service-variables"
          encrypted_variables_kvm: "identity-service-variables-encrypted"
          identity_target_server: "identity-server"
