name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Identity-Service-Build"
    trigger:
      branches:
        exclude:
          - master
          - refs/heads/master
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    ping: false
    jinja_templates:
      IDENTITY_PROVIDER_CIS2: cis2
      IDENTITY_PROVIDER_NHS_LOGIN: nhs-login
      VARIABLES_KVM: identity-service-internal-dev-DEV-variables
      ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
      NUM_RANDOM_LONG_INTS_FOR_STATE: 4
    apigee_deployments:
      - environment: internal-dev
        # post_deploy:
        #   - template: ./templates/run-integration-tests.yml
        #     parameters:
        #       service_name: ${{ variables.service_name }}
      - environment: internal-dev
        service_name: ${{ variables.service_name }}-int
        short_service_name: ${{ variables.short_service_name }}-int
        product_display_name: ${{ variables.product_display_name }} (INT Testing)
        stage_name: internal_dev_int
        service_base_path: ${{ variables.service_base_path }}-int
        jinja_templates:
          IDENTITY_PROVIDER_CIS2: cis2-int
          IDENTITY_PROVIDER_NHS_LOGIN: nhs-login
          VARIABLES_KVM: identity-service-internal-dev-int-variables
          ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
          NUM_RANDOM_LONG_INTS_FOR_STATE: 4
