name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Identity-Service-Build"
    trigger:
      branches:
        exclude:
          - master
          - refs/heads/master
          - refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    ping: false
    jinja_templates:
      IDENTITY_TARGET_SERVER: identity-server
      VARIABLES_KVM: identity-service-variables
      ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
    secret_ids:
      - ptl/app-credentials/internal-dev/INTERNAL_TESTING_WITHOUT_ASID_KEY
      - ptl/app-credentials/internal-dev/INTERNAL_TESTING_WITHOUT_ASID_SECRET
      - ptl/app-credentials/internal-dev/INTERNAL_TESTING_WITH_ASID_KEY
      - ptl/app-credentials/internal-dev/INTERNAL_TESTING_WITH_ASID_SECRET
    apigee_deployments:
      - environment: internal-dev
        post_deploy:
          - template: azure/common/deploy-app.yml@self
            parameters:
              attributes:
                asid: 12345
          - bash: echo "test"
          - template: azure/common/deploy-app.yml@self
            parameters:
              attributes:
                asid: 12345
