name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

variables:
  SERVICE_NAME: identity-service
  SERVICE_BASE_PATH: /oauth2
  VARIABLES_KVM: identity-service-variables
  ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
  IDENTITY_TARGET_SERVER: identity-server
  SPEC_FILE_NAME: identity-service
  PROXY_NAME: live

resources:
  pipelines:
  - pipeline: identity-service
    source: "Identity-Service-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: DeployInternalDev
  displayName: internal-dev
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'internal-dev'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: components/get-aws-secrets-and-ssm-params.yml
                parameters:
                  SECRET_IDS: >
                    ptl/azure-devops/apigee-nonprod/APIGEE_OTP_KEY
                    ptl/azure-devops/apigee-nonprod/APIGEE_PASSWORD
                    ptl/access-tokens/github/repo-status-update/GITHUB_ACCESS_TOKEN
                  PARAM_NAMES: >
                    /ptl/azure-devops/apigee-nonprod/APIGEE_USERNAME
                    /ptl/azure-devops/apigee-nonprod/APIGEE_ORGANIZATION
                    /ptl/azure-devops/env-internal-dev/APIGEE_ENVIRONMENT
                    /ptl/azure-devops/env-internal-dev/ENV_URL
                    /ptl/azure-devops/env-internal-dev/IDENTITY_URL
                    /ptl/azure-devops/GITHUB_USER
              - template: templates/identity-service-templating.yml
              - template: templates/deploy-service.yml

- stage: DeployInternalQA
  displayName: internal-qa
  dependsOn: DeployInternalDev
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'internal-qa'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: components/get-aws-secrets-and-ssm-params.yml
                parameters:
                  SECRET_IDS: >
                    ptl/azure-devops/apigee-nonprod/APIGEE_OTP_KEY
                    ptl/azure-devops/apigee-nonprod/APIGEE_PASSWORD
                    ptl/access-tokens/github/repo-status-update/GITHUB_ACCESS_TOKEN
                  PARAM_NAMES: >
                    /ptl/azure-devops/apigee-nonprod/APIGEE_USERNAME
                    /ptl/azure-devops/apigee-nonprod/APIGEE_ORGANIZATION
                    /ptl/azure-devops/env-internal-qa/APIGEE_ENVIRONMENT
                    /ptl/azure-devops/env-internal-qa/ENV_URL
                    /ptl/azure-devops/env-internal-qa/IDENTITY_URL
                    /ptl/azure-devops/GITHUB_USER
              - template: templates/identity-service-templating.yml
              - template: templates/deploy-service.yml

- stage: DeployInternalQASandbox
  displayName: internal-qa-sandbox
  dependsOn: DeployInternalDev
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'internal-qa-sandbox'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: components/get-aws-secrets-and-ssm-params.yml
                parameters:
                  SECRET_IDS: >
                    ptl/azure-devops/apigee-nonprod/APIGEE_OTP_KEY
                    ptl/azure-devops/apigee-nonprod/APIGEE_PASSWORD
                    ptl/access-tokens/github/repo-status-update/GITHUB_ACCESS_TOKEN
                  PARAM_NAMES: >
                    /ptl/azure-devops/apigee-nonprod/APIGEE_USERNAME
                    /ptl/azure-devops/apigee-nonprod/APIGEE_ORGANIZATION
                    /ptl/azure-devops/env-internal-qa-sandbox/APIGEE_ENVIRONMENT
                    /ptl/azure-devops/env-internal-qa-sandbox/ENV_URL
                    /ptl/azure-devops/env-internal-qa-sandbox/IDENTITY_URL
                    /ptl/azure-devops/GITHUB_USER
              - template: templates/identity-service-templating.yml
              - template: templates/deploy-service.yml

- stage: DeployInternalPortal
  displayName: internal-portal
  dependsOn: DeployInternalDev
  jobs:
    - deployment: DeploySpecs
      displayName: Deploy Specs
      environment: 'internal-portal'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: components/get-aws-secrets-and-ssm-params.yml
                parameters:
                  SECRET_IDS: >
                    ptl/azure-devops/apigee-nonprod/APIGEE_OTP_KEY
                    ptl/azure-devops/apigee-nonprod/APIGEE_PASSWORD
                    ptl/access-tokens/github/repo-status-update/GITHUB_ACCESS_TOKEN
                  PARAM_NAMES: >
                    /ptl/azure-devops/apigee-nonprod/APIGEE_USERNAME
                    /ptl/azure-devops/apigee-nonprod/APIGEE_ORGANIZATION
                    /ptl/azure-devops/env-internal-portal/APIGEE_ENVIRONMENT
                    /ptl/azure-devops/GITHUB_USER
              - template: templates/deploy-specs.yml

- stage: DeployRef
  displayName: ref
  dependsOn: 
    - DeployInternalQA
    - DeployInternalQASandbox
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'ref'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: components/get-aws-secrets-and-ssm-params.yml
                parameters:
                  SECRET_IDS: >
                    ptl/azure-devops/apigee-nonprod/APIGEE_OTP_KEY
                    ptl/azure-devops/apigee-nonprod/APIGEE_PASSWORD
                    ptl/access-tokens/github/repo-status-update/GITHUB_ACCESS_TOKEN
                  PARAM_NAMES: >
                    /ptl/azure-devops/apigee-nonprod/APIGEE_USERNAME
                    /ptl/azure-devops/apigee-nonprod/APIGEE_ORGANIZATION
                    /ptl/azure-devops/env-ref/APIGEE_ENVIRONMENT
                    /ptl/azure-devops/env-ref/ENV_URL
                    /ptl/azure-devops/env-ref/IDENTITY_URL
                    /ptl/azure-devops/GITHUB_USER
              - template: templates/identity-service-templating.yml
              - template: templates/deploy-service.yml

- stage: DeployDev
  displayName: dev
  dependsOn: 
    - DeployRef
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'dev'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: components/get-aws-secrets-and-ssm-params.yml
                parameters:
                  SECRET_IDS: >
                    ptl/azure-devops/apigee-prod/APIGEE_OTP_KEY
                    ptl/azure-devops/apigee-prod/APIGEE_PASSWORD
                    ptl/access-tokens/github/repo-status-update/GITHUB_ACCESS_TOKEN
                  PARAM_NAMES: >
                    /ptl/azure-devops/apigee-prod/APIGEE_USERNAME
                    /ptl/azure-devops/apigee-prod/APIGEE_ORGANIZATION
                    /ptl/azure-devops/env-dev/APIGEE_ENVIRONMENT
                    /ptl/azure-devops/env-dev/ENV_URL
                    /ptl/azure-devops/env-dev/IDENTITY_URL
                    /ptl/azure-devops/GITHUB_USER
              - template: templates/identity-service-templating.yml
              - template: templates/deploy-service.yml

- stage: DeployProd
  displayName: prod
  dependsOn: 
    - DeployRef
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'prod'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: components/get-aws-secrets-and-ssm-params.yml
                parameters:
                  SECRET_IDS: >
                    prod/azure-devops/apigee-prod/APIGEE_OTP_KEY
                    prod/azure-devops/apigee-prod/APIGEE_PASSWORD
                    ptl/access-tokens/github/repo-status-update/GITHUB_ACCESS_TOKEN
                  PARAM_NAMES: >
                    /prod/azure-devops/apigee-prod/APIGEE_USERNAME
                    /prod/azure-devops/apigee-prod/APIGEE_ORGANIZATION
                    /prod/azure-devops/env-prod/APIGEE_ENVIRONMENT
                    /prod/azure-devops/env-prod/ENV_URL
                    /prod/azure-devops/env-prod/IDENTITY_URL
                    /ptl/azure-devops/GITHUB_USER
              - template: templates/identity-service-templating.yml
              - template: templates/deploy-service.yml

- stage: DeploySandbox
  displayName: sandbox
  dependsOn: 
    - DeployRef
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'sandbox'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: components/get-aws-secrets-and-ssm-params.yml
                parameters:
                  SECRET_IDS: >
                    ptl/azure-devops/apigee-nonprod/APIGEE_OTP_KEY
                    ptl/azure-devops/apigee-nonprod/APIGEE_PASSWORD
                    ptl/access-tokens/github/repo-status-update/GITHUB_ACCESS_TOKEN
                  PARAM_NAMES: >
                    /ptl/azure-devops/apigee-nonprod/APIGEE_USERNAME
                    /ptl/azure-devops/apigee-nonprod/APIGEE_ORGANIZATION
                    /plt/azure-devops/env-sandbox/APIGEE_ENVIRONMENT
                    /plt/azure-devops/env-sandbox/ENV_URL
                    /plt/azure-devops/env-sandbox/IDENTITY_URL
                    /ptl/azure-devops/GITHUB_USER
              - template: templates/identity-service-templating.yml
              - template: templates/deploy-service.yml

- stage: DeployInt
  displayName: int
  dependsOn: 
    - DeployRef
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'int'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: components/get-aws-secrets-and-ssm-params.yml
                parameters:
                  SECRET_IDS: >
                    ptl/azure-devops/apigee-nonprod/APIGEE_OTP_KEY
                    ptl/azure-devops/apigee-nonprod/APIGEE_PASSWORD
                    ptl/access-tokens/github/repo-status-update/GITHUB_ACCESS_TOKEN
                  PARAM_NAMES: >
                    /ptl/azure-devops/apigee-nonprod/APIGEE_USERNAME
                    /ptl/azure-devops/apigee-nonprod/APIGEE_ORGANIZATION
                    /plt/azure-devops/env-int/APIGEE_ENVIRONMENT
                    /plt/azure-devops/env-int/ENV_URL
                    /plt/azure-devops/env-int/IDENTITY_URL
                    /ptl/azure-devops/GITHUB_USER
              - template: templates/identity-service-templating.yml
              - template: templates/deploy-service.yml

- stage: DeployIntNoSmartCard
  displayName: int no-smartcard
  dependsOn: 
    - DeployRef
  variables:
    - name: IDENTITY_TARGET_SERVER
      value: identity-server-no-smartcard
    - name: SERVICE_BASE_PATH
      value: oauth2-no-smartcard
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'int-no-smartcard'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: components/get-aws-secrets-and-ssm-params.yml
                parameters:
                  SECRET_IDS: >
                    ptl/azure-devops/apigee-nonprod/APIGEE_OTP_KEY
                    ptl/azure-devops/apigee-nonprod/APIGEE_PASSWORD
                    ptl/access-tokens/github/repo-status-update/GITHUB_ACCESS_TOKEN
                  PARAM_NAMES: >
                    /ptl/azure-devops/apigee-nonprod/APIGEE_USERNAME
                    /ptl/azure-devops/apigee-nonprod/APIGEE_ORGANIZATION
                    /plt/azure-devops/env-int/APIGEE_ENVIRONMENT
                    /plt/azure-devops/env-int/ENV_URL
                    /plt/azure-devops/env-int/IDENTITY_URL
                    /ptl/azure-devops/GITHUB_USER
              - template: templates/identity-service-templating.yml
              - template: templates/deploy-service.yml

- stage: DeployPortal
  displayName: portal
  dependsOn: []
  jobs:
    - deployment: DeploySpecs
      displayName: Deploy Specs
      condition: false
      environment: 'portal'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: components/get-aws-secrets-and-ssm-params.yml
                parameters:
                  SECRET_IDS: >
                    ptl/azure-devops/apigee-nonprod/APIGEE_OTP_KEY
                    ptl/azure-devops/apigee-nonprod/APIGEE_PASSWORD
                    ptl/access-tokens/github/repo-status-update/GITHUB_ACCESS_TOKEN
                  PARAM_NAMES: >
                    /ptl/azure-devops/apigee-prod/APIGEE_USERNAME
                    /ptl/azure-devops/apigee-prod/APIGEE_ORGANIZATION
                    /plt/azure-devops/env-portal/APIGEE_ENVIRONMENT
                    /ptl/azure-devops/GITHUB_USER
              - template: templates/deploy-specs.yml
