name: "$(SourceBranchName)+$(BuildID)"

# Prevents building every commit or on PR
trigger: none
pr: none

# Consume an artifact from the build pipeline as soon as it becomes available.
resources:
  pipelines:
  - pipeline: identity-service
    source: Identity-Service-Build
    trigger:
      branches:
        exclude:
          - "master"
          - "refs/heads/master"
          - "refs/tags/v*"

variables:
  SERVICE_NAME: identity-service
  SERVICE_BASE_PATH: /oauth2
  VARIABLES_KVM: identity-service-variables
  ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
  IDENTITY_TARGET_SERVER: identity-server
  FORCE_SANDBOX: false
  NAMESPACE: from_branchname
  PROXY_NAME: live
  GITHUB_ACCESS_TOKEN: $(GITHUB_ACCESS_TOKEN)


pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: DeployInternalDev
    displayName: internal-dev
    variables:
    - name: aws-label-ptl-or-prod
      value: ptl
    - name: aws-label-apigee-org
      value: apigee-nonprod
    - name: aws-label-apigee-env
      value: env-internal-dev
    jobs:
      - deployment: DeployService
        displayName: Deploy Service
        environment: 'internal-dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: components/notify-github-pending.yml
                - template: components/get-aws-secrets-and-ssm-params.yml
                - template: templates/identity-service-templating.yml
                - template: templates/setup-build-name.yml
                - template: templates/deploy-namespaced-service.yml
                - template: components/notify-github-finished.yml
