name: Identity Service Pull Request

trigger: none

pr:
  branches:
    include:
      - APM-*
      - apm-*

resources:
  pipelines:
  - pipeline: IdentityService
    source: "NHSDigital.identity-service-api"


parameters:
  - name : artifactBranch
    displayName: Artifact Branch (e.g. feature/myfeature)
    type: string
    default: $(Build.SourceBranch)
  - name : artifactBuildId
    displayName: Artifact Build Id (e.g. run Id for the build to download). Overrides Artifact Branch if not "latest".
    type: string
    default: latest

variables:
  SERVICE_NAME: identity-service
  SERVICE_BASE_PATH: /oauth2
  VARIABLES_KVM: identity-service-variables
  ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
  IDENTITY_TARGET_SERVER: identity-server
  FORCE_SANDBOX: false
  NAMESPACE: from_branchname

pool:
  vmImage: 'ubuntu-18.04'

# stages:
#   - stage: DeployInternalDev
#     displayName: internal-dev
#     variables:
#     - group: apigee-nonprod
#     - group: env-internal-dev
#     jobs:
#       - deployment: DeployService
#         displayName: Deploy Service
#         environment: 'internal-dev'
#         strategy:
#           runOnce:
#             deploy:
#               steps:
#                 - template: templates/identity-service-templating.yml
#                 - template: templates/deploy-namespaced-service.yml

stages:
- stage: DeployInternalDev
  displayName: internal-dev
  variables:
  - group: apigee-nonprod
  - group: env-internal-dev
  jobs:
    - job: DeployService
      displayName: Deploy Service
      steps:
        - checkout: none
        - task: DownloadPipelineArtifact@2
          displayName: 'Download Build Artifact'
          inputs:
            source: 'specific'
            project: '$(resources.pipeline.IdentityService.projectID)'
            definition: '$(resources.pipeline.IdentityService.pipelineID)'
            preferTriggeringPipeline: true
            ${{ if eq(parameters.artifactBuildId, 'latest') }}:
              buildVersionToDownload: 'latestFromBranch'
            ${{ if ne(parameters.artifactBuildId, 'latest') }}:
              buildVersionToDownload: 'specific'
              runId: '${{ parameters.artifactBuildId }}'
            ${{ if eq(parameters.artifactBranch, '$(Build.SourceBranch)') }}:
              branchName: '$(Build.SourceBranch)'
            ${{ if ne(parameters.artifactBranch, '$(Build.SourceBranch)') }}:
              branchName: 'refs/heads/${{ parameters.artifactBranch }}'
            downloadPath: '$(Pipeline.Workspace)/$(SERVICE_NAME)'
        - bash: ls $(Pipeline.Workspace)
        - bash: ls $(Pipeline.Workspace)/$(SERVICE_NAME)
        - template: templates/identity-service-templating.yml
        - template: templates/deploy-namespaced-service.yml
