name: "$(SourceBranchName)+$(BuildID)"

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ['*']

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-build.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    python_version: ${{ variables.python_version }}
    cache_steps:
      - task: s3-cache-action@1
        inputs:
          key: 'node modules | ./package-lock.json'
          location: './node_modules'
          debug: true
          workingDirectory: '${{ variables.service_name }}'
        displayName: cache  node modules
      - task: s3-cache-action@1
        inputs:
          key: 'poetry | ./poetry.lock'
          location: './.venv'
          debug: true
          workingDirectory: '${{ variables.service_name }}'
        displayName: cache python dependencies
