name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

variables:
  SERVICE_NAME: identity-service
  SERVICE_BASE_PATH: /oauth2
  VARIABLES_KVM: identity-service-variables
  ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
  IDENTITY_TARGET_SERVER: identity-server
  SPEC_FILE_NAME: identity-service
  PROXY_NAME: live

resources:
  pipelines:
  - pipeline: identity-service
    source: "Identity-Service-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: DeployInternalDev
  displayName: internal-dev
  variables:
  - name: aws-label-ptl-or-prod
    value: ptl
  - name: aws-label-apigee-org
    value: apigee-nonprod
  - name: aws-label-apigee-env
    value: env-internal-dev

  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'internal-dev'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: components/get-aws-secrets-and-ssm-params.yml
              - template: templates/identity-service-templating.yml
              - template: templates/deploy-service.yml

- stage: DeployInternalQA
  displayName: internal-qa
  dependsOn: DeployInternalDev
  variables:
    - name: aws-label-ptl-or-prod
      value: ptl
    - name: aws-label-apigee-org
      value: apigee-nonprod
    - name: aws-label-apigee-env
      value: env-internal-qa
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'internal-qa'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: components/get-aws-secrets-and-ssm-params.yml
              - template: templates/identity-service-templating.yml
              - template: templates/deploy-service.yml

- stage: DeployInternalQASandbox
  displayName: internal-qa-sandbox
  dependsOn: DeployInternalDev
  variables:
    - name: aws-label-ptl-or-prod
      value: ptl
    - name: aws-label-apigee-org
      value: apigee-nonprod
    - name: aws-label-apigee-env
      value: env-internal-qa-sandbox
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'internal-qa-sandbox'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: components/get-aws-secrets-and-ssm-params.yml
              - template: templates/identity-service-templating.yml
              - template: templates/deploy-service.yml

- stage: DeployInternalPortal
  displayName: internal-portal
  dependsOn: DeployInternalDev
  variables:
    - name: aws-label-ptl-or-prod
      value: ptl
    - name: aws-label-apigee-org
      value: apigee-nonprod
    - name: aws-label-apigee-env
      value: env-internal-portal
  jobs:
    - deployment: DeploySpecs
      displayName: Deploy Specs
      environment: 'internal-portal'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: components/get-aws-secrets-and-ssm-params.yml
              - template: templates/deploy-specs.yml

- stage: DeployRef
  displayName: ref
  dependsOn: 
    - DeployInternalQA
    - DeployInternalQASandbox
  variables:
    - name: aws-label-ptl-or-prod
      value: ptl
    - name: aws-label-apigee-org
      value: apigee-nonprod
    - name: aws-label-apigee-env
      value: env-ref
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'ref'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: components/get-aws-secrets-and-ssm-params.yml
              - template: templates/identity-service-templating.yml
              - template: templates/deploy-service.yml

- stage: DeployDev
  displayName: dev
  dependsOn: 
    - DeployRef
  variables:
    - name: aws-label-ptl-or-prod
      value: prod
    - name: aws-label-apigee-org
      value: apigee-prod
    - name: aws-label-apigee-env
      value: env-dev
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'dev'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: components/get-aws-secrets-and-ssm-params.yml
              - template: templates/identity-service-templating.yml
              - template: templates/deploy-service.yml

- stage: DeployProd
  displayName: prod
  dependsOn: 
    - DeployRef
  variables:
    - name: aws-label-ptl-or-prod
      value: prod
    - name: aws-label-apigee-org
      value: apigee-prod
    - name: aws-label-apigee-env
      value: env-prod
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'prod'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: components/get-aws-secrets-and-ssm-params.yml
              - template: templates/identity-service-templating.yml
              - template: templates/deploy-service.yml

- stage: DeploySandbox
  displayName: sandbox
  dependsOn: 
    - DeployRef
  variables:
    - name: aws-label-ptl-or-prod
      value: prod
    - name: aws-label-apigee-org
      value: apigee-prod
    - name: aws-label-apigee-env
      value: env-sandbox
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'sandbox'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: components/get-aws-secrets-and-ssm-params.yml
              - template: templates/identity-service-templating.yml
              - template: templates/deploy-service.yml

- stage: DeployInt
  displayName: int
  dependsOn: 
    - DeployRef
  variables:
    - name: aws-label-ptl-or-prod
      value: prod
    - name: aws-label-apigee-org
      value: apigee-prod
    - name: aws-label-apigee-env
      value: env-int
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'int'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: components/get-aws-secrets-and-ssm-params.yml
              - template: templates/identity-service-templating.yml
              - template: templates/deploy-service.yml

- stage: DeployIntNoSmartCard
  displayName: int no-smartcard
  dependsOn: 
    - DeployRef
  variables:
    - name: aws-label-ptl-or-prod
      value: prod
    - name: aws-label-apigee-org
      value: apigee-prod
    - name: aws-label-apigee-env
      value: env-int
    - name: IDENTITY_TARGET_SERVER
      value: identity-server-no-smartcard
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'int-no-smartcard'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: components/get-aws-secrets-and-ssm-params.yml
              - template: templates/identity-service-templating.yml
              - template: templates/deploy-service.yml

- stage: DeployPortal
  displayName: portal
  dependsOn: []
  variables:
    - name: aws-label-ptl-or-prod
      value: prod
    - name: aws-label-apigee-org
      value: apigee-prod
    - name: aws-label-apigee-env
      value: env-portal
  jobs:
    - deployment: DeploySpecs
      displayName: Deploy Specs
      condition: false
      environment: 'portal'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: components/get-aws-secrets-and-ssm-params.yml
              - template: templates/deploy-specs.yml
