name: Identity Service Pull Request

pr:
  branches:
    include:
      - APM-*
      - apm-*

variables:
  SERVICE_NAME: IdentityService
  SERVICE_BASE_PATH: /oauth2
  VARIABLES_KVM: identity-service-variables
  ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
  IDENTITY_TARGET_SERVER: identity-server
  FORCE_SANDBOX: false
  NAMESPACE: from_branchname

resources:
  pipelines:
  - pipeline: IdentityService
    source: NHSDigital.identity-service-api

pool:
  vmImage: 'ubuntu-18.04'

stages:
- stage: DeployInternalDev
  displayName: internal-dev
  variables:
  - group: apigee-nonprod
  - group: env-internal-dev
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'internal-dev'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: templates/identity-service-templating.yml
              - template: templates/deploy-namespaced-service.yml
