name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Identity-Service-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    enable_monitoring: true
    jinja_templates:
      IDENTITY_PROVIDER_CIS2: cis2
      IDENTITY_PROVIDER_NHS_LOGIN: nhs-login
      VARIABLES_KVM: identity_service_config
      ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
      NUM_RANDOM_LONG_INTS_FOR_STATE: 4
    apigee_deployments:
      - environment: internal-dev
        post_deploy:
          - template: ./templates/run-integration-tests.yml
            parameters:
              test_type: e2e
      - environment: internal-dev-sandbox
      - environment: internal-qa
        depends_on:
          - internal_dev
      - environment: internal-qa-sandbox
        depends_on:
          - internal_dev
      - environment: ref
      - environment: dev
      - environment: sandbox # required for hello-world https://portal.developer.nhs.uk/docs/hello-world-sandbox/1/routes/hello/application/get
      - environment: int
      - environment: int
        stage_name: int_no_smartcard
        fully_qualified_service_name: identity-service-int-no-smartcard
        service_base_path: oauth2-no-smartcard
        jinja_templates:
          IDENTITY_PROVIDER_CIS2: cis2-no-smartcard
          IDENTITY_PROVIDER_NHS_LOGIN: nhs-login
          VARIABLES_KVM: identity_service_config_no_smartcard
          ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted-no-smartcard
          NUM_RANDOM_LONG_INTS_FOR_STATE: 4
      - environment: prod
