name: Identity Service Release

trigger: none

variables:
  SERVICE_NAME: IdentityService
  SERVICE_BASE_PATH: /oauth2
  VARIABLES_KVM: identity-service-variables
  ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
  IDENTITY_TARGET_SERVER: identity-server
  SPEC_FILE_NAME: identity-service

resources:
  pipelines:
  - pipeline: IdentityService
    source: NHSDigital.identity-service-api

pool:
  vmImage: 'ubuntu-18.04'

stages:
- stage: DeployInternalDev
  displayName: internal-dev
  variables:
  - group: apigee-nonprod
  - group: env-internal-dev
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'internal-dev'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: templates/identity-service-templating.yml
              - template: templates/deploy-service.yml

- stage: DeployInternalQA
  displayName: internal-qa
  dependsOn: DeployInternalDev
  variables:
    - group: apigee-nonprod
    - group: env-internal-qa
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'internal-qa'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: templates/identity-service-templating.yml
              - template: templates/deploy-service.yml

- stage: DeployInternalQASandbox
  displayName: internal-qa-sandbox
  dependsOn: DeployInternalDev
  variables:
    - group: apigee-nonprod
    - group: env-internal-qa-sandbox
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'internal-qa-sandbox'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: templates/identity-service-templating.yml
              - template: templates/deploy-service.yml

- stage: DeployInternalPortal
  displayName: internal-portal
  dependsOn: DeployInternalDev
  variables:
    - group: apigee-nonprod
    - group: env-internal-portal
  jobs:
    - deployment: DeploySpecs
      displayName: Deploy Specs
      environment: 'internal-portal'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: templates/deploy-specs.yml
