variables:
  service_name: identity-service
  short_service_name: ids
  service_base_path: oauth2
  product_display_name: Identity Service
  product_description: Placeholder description
  ratelimiting: |
    {
      "app": {
        "quota": {
          "limit": 300,
          "interval": 1,
          "timeunit": "minute",
          "enabled": true
        },
        "spikeArrest": {
          "enabled": false
        }
      },
      "proxy": {
        "quota": {
          "enabled": false
        },
        "spikeArrest": {
          "ratelimit": "300000pm",
          "enabled": true
        }
      }
    }
  default_keycloak_jinja_templates:
    IDENTITY_PROVIDER_CIS2: cis2-keycloak
    IDENTITY_PROVIDER_NHS_LOGIN: nhs-login-keycloak
    VARIABLES_KVM: identity_service_config_keycloak
    ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
    ENCRYPTED_VARIABLES_KVM_KEY_CLIENT_SECRET: keycloak_client_secret
    NUM_RANDOM_LONG_INTS_FOR_STATE: 4
    RATELIMITING: ${{ variables.ratelimiting }}
  default_jinja_templates:
    IDENTITY_PROVIDER_CIS2: cis2
    IDENTITY_PROVIDER_NHS_LOGIN: nhs-login
    VARIABLES_KVM: identity_service_config
    ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted
    NUM_RANDOM_LONG_INTS_FOR_STATE: 4
    RATELIMITING: ${{ variables.ratelimiting }}
