variables:
  service_name: identity-service
  short_service_name: ids
  service_base_path: oauth2
  product_display_name: Identity Service
  product_description: Placeholder description
  spec_file: identity-service.json
