version: 2
updates:

  # ---------------------------
  # Python (Poetry via pip)
  # ---------------------------
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    labels: [ "dependencies", "python", "poetry" ]
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]

  # ---------------------------
  # NodeJS (root)
  # ---------------------------
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    labels: [ "dependencies", "npm" ]
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]

  # ---------------------------
  # GitHub Actions
  # ---------------------------
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    labels: [ "dependencies", "github-actions" ]
    cooldown:
      default-days: 7
