name: Identity Service Release

trigger: none

resources:
  pipelines:
  - pipeline: IdentityServiceAPIArtifact
    source: NHSDigital.identity-service-api

pool:
  vmImage: 'ubuntu-18.04'

stages:
- stage: DeployInternalDev
  displayName: internal-dev
  variables:
  - group: apigee-nonprod
  - group: env-internal-dev
  jobs:
    - deployment: DeployService
      displayName: Deploy Service
      environment: 'internal-dev'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: templates/identity-service-templating.yml
                parameters:
                  SERVICE_NAME: identity-service
              - template: templates/deploy-service.yml

- stage: DeployInternalDevSandbox
  displayName: internal-dev (sandbox)
  jobs:
  - job: DeployInternalDevSandbox
    steps:
    - script: echo second stage
