name: Identity Service Release

trigger: none

resources:
  pipelines:
  - pipeline: IdentityServiceApiArtifact
    source: "$(SourceBranchName)+$(BuildID)"

pool:
  vmImage: 'ubuntu-18.04'

stages:
- stage: internal-dev
  jobs:
  - job: DeployInternalDev
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - script: echo my first build job
- stage: internal-dev (sandbox)
  jobs:
  - job: DeployInternalDevSandbox
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - script: echo second stage
