name: Identity Service Release

trigger: none

resources:
  pipelines:
  - pipeline: identity-service-api-artifact
    source: $(SourceBranchName)+$(BuildID)

pool:
  vmImage: 'ubuntu-18.04'

stages:
- stage: internal-dev
  jobs:
  - job: Deploy internal-dev
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - script: echo my first build job
- stage: internal-dev (sandbox)
  jobs:
  - job: Deploy internal-dev (sandbox)
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - script: echo second stage
