name: Identity Service Release

trigger: none

resources:
  pipelines:
  - pipeline: IdentityServiceAPIArtifact
    source: NHSDigital.identity-service-api

pool:
  vmImage: 'ubuntu-18.04'

stages:
- stage: DeployService
  displayName: internal-dev
  jobs:
  - job: DeployInternalDev
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - script: echo my first build job
- stage: DeployService
  displayName: internal-dev (sandbox)
  jobs:
  - job: DeployInternalDevSandbox
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - script: echo second stage
