name: Identity Service Release

resources:
  pipelines:
  - pipeline: Identity Service API
    source: NHSDigital.identity-service-api
    trigger:
      branches:
      - master

trigger: none

pool:
  vmImage: 'ubuntu-18.04'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo Building!
- stage: Test
  jobs:
  - job: TestOnWindows
    steps:
    - script: echo Testing on Windows!
  - job: TestOnLinux
    steps:
    - script: echo Testing on Linux!
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying the code!