# This is an OpenAPI Specification (https://swagger.io/specification/)
# for the Personal Demographics Service (PDS) API
# owned by NHS Digital (https://digital.nhs.uk/)
openapi: "3.0.0"
info:
  version: "{VERSION}"
  title: Template API
  description: |
    ## Overview
    TODO
    
    You can:
    * TODO

    You cannot currently use this API to:
    * TODO
    
    You can access the following data:
    * TODO

    ## Related APIs
    TODO
    
    ## API status and roadmap
    TODO
    
    The following items are on our roadmap, in rough priority order:
    - TODO
    
    We are extremely keen to receive feedback on the API during alpha and beta,
    for example if there are data fields missing that you think you need.
    Please [get in touch](/help-and-support) with any comments or suggestions.

    ## Technology
    This API is [RESTful](/introduction-to-apis#basic-rest).

    It also conforms to the [FHIR](/introduction-to-apis#fhir) global standard for health care data exchange.
    Specifically, it is aligned with [FHIR UK Core](https://digital.nhs.uk/services/fhir-uk-core), which is built on FHIR Release 4.

    You don’t need to know much about FHIR to use this API - FHIR APIs are just RESTful APIs that follow specific rules.
    In particular:
    - resource names are capitalised and singular, for example the `/Patient` not `/patients`
    - array names are singular, for example `line` not `lines` for address lines
    - data items that are country-specific and thus not included in the FHIR global base resources are usually wrapped in an `extension` object

    This API is available on the Internet, although access using NHS smartcards (see below)
    currently requires a connection to the [Health and Social Care Network (HSCN)](https://digital.nhs.uk/services/health-and-social-care-network).

    ## Authorisation
    TODO
    
    ## Testing
    You can test this API in:
    * our [sandbox environment](/testing#sandbox-testing) for initial developer testing
    * our [integration test environment](/testing#integration-testing) for formal integration testing (coming soon)

    Our sandbox environment is a very basic simulation of the live service. It only covers a limited set of scenarios and is stateless, so does not actually persist any updates.

    For more details on sandbox testing, or to try out the sandbox using our "Try this API" feature, see the documentation for each endpoint.

    Alternatively, you can try out the sandbox using our Postman collection:

    [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/2871d49488699f3f5a67)

    ## Assurance
    We are hoping to make the assurance process as lightweight and as self-service as possible.

    More details to follow.

    ## Endpoints
    TODO
  contact:
    name: Template API Support
    url: 'https://tbc.api.nhs.net'
    email: tbc-api-support@nhs.net
servers:
  - url: 'https://emea-demo8-test.apigee.net/TODO sandbox endpoint'
    description: Sandbox service.
tags:
  - name: #TODO declare tags
paths:
#TODO add endpoints
