name: SBOM Check

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Apply SBOM check"
        required: true
        type: choice
        options:
          - apply
          - skip
        default: apply

jobs:
  sbom-check:
    if: ${{ github.event.inputs.environment == 'apply' }}
    name: Software Bill of Materials
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      
      - name: Update apt repositories
        run: sudo apt update

      - name: Install Java
        run: sudo apt-get install --yes default-jre default-jdk

      - name: Install node
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Upgrade python packaging tools
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install poetry
        run: pip install "poetry<2.0.0"

      - name: Cache poetry packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-build-cache-poetry-packages-${{ hashFiles('**/poetry.lock') }}

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-cache-npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install repo
        run: make install

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: ./
          format: cyclonedx-json
          artifact-name: identity-repo-sbom.cdx.json
          
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-action-${{ github.run_id }}
          path: /tmp/sbom-action-*/identity-repo-sbom.cdx.json
          if-no-files-found: warn

      - name: Clean up SBOM file
        run: rm /tmp/sbom-action-*/identity-repo-sbom.cdx.json || true

